apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: thanos-query
    app.kubernetes.io/instance: thanos-query
    app.kubernetes.io/name: thanos
    app.kubernetes.io/version: v0.10.1
  name: thanos-query
  namespace: thanos
spec:
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
  - name: http
    port: 9090
    targetPort: http
  selector:
    app.kubernetes.io/component: thanos-query
    app.kubernetes.io/instance: thanos-query
    app.kubernetes.io/name: thanos
