apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: thanos-receive
  namespace: thanos
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/component: database-write-hashring
      app.kubernetes.io/instance: thanos-receive
      app.kubernetes.io/name: thanos-receive
