apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: query-cache
    app.kubernetes.io/instance: thanos-query-frontend
    app.kubernetes.io/name: thanos-query-frontend
    app.kubernetes.io/version: v0.16.0
  name: thanos-query-frontend
  namespace: thanos
spec:
  ports:
  - name: http
    port: 9090
    targetPort: http
  selector:
    app.kubernetes.io/component: query-cache
    app.kubernetes.io/instance: thanos-query-frontend
    app.kubernetes.io/name: thanos-query-frontend
